In [1]:
import numpy as np
import pandas as pd

np.random.seed(123)

### 1. How likely is it that you roll doubles when rolling two dice?

In [1]:

outcomes1 = [1,2,3,4,5,6]
outcomes2 = [1,2,3,4,5,6]


dbl_rolls = []
for (x,y) in zip(outcomes1, outcomes2):
    dbl_rolls.append((x,y))
print(dbl_rolls)
print(len(dbl_rolls))

rolls = []  
for i in outcomes1:
    for j in outcomes2:
        rolls.append((i,j))
print(rolls)
print(len(rolls))

print(len(dbl_rolls)/len(rolls))


[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]
6
[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)]
36
0.16666666666666666


In [154]:
n_trials = 10_000 

n_dice = 2

outcome = [1,2,3,4,5,6]

rolls = np.random.choice(outcome, size = (n_trials, n_dice))

rolls[:,0] == rolls[:,1]

(rolls[:,0] == rolls[:,1]).mean()

0.1655

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [12]:
#outcomes
outcomes = ['H','T']

#simulations & trials
n_trials = 8 #8 coin flips
n_simulations = 100_000 #how many times we're flipping the 3 coins
#set up number of simulations and number of coin flips
coin_flips = np.random.choice(outcomes, (n_simulations, n_trials))
coin_flips                #(outcomes=heads,tails.  (sims #of rows, 3coins #of columns))
#be sure to sum across each simulation aka across each row (axis=1)
head_counts = (coin_flips == 'H').sum(axis=1)
(head_counts == 3).mean()

0.21934

What is the probability of getting more than 3 heads?

In [13]:
outcomes = ['H','T']

#simulations & trials
n_trials = 8 #8 coin flips
n_simulations = 100_000 #how many times we're flipping the 3 coins
#set up number of simulations and number of coin flips
coin_flips = np.random.choice(outcomes, (n_simulations, n_trials))
coin_flips                #(outcomes=heads,tails.  (sims #of rows, 3coins #of columns))
#be sure to sum across each simulation aka across each row (axis=1)
head_counts = (coin_flips == 'H').sum(axis=1)
(head_counts > 3).mean()

0.63469

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [19]:
#outcomes
outcomes3 = ['W','W','W','D']

#simulations & trials

#simulations & trials
n_trials = 2 #8 coin flips
n_simulations = 100_000 #how many times we're flipping the 3 coins
#set up number of simulations and number of coin flips
cohort_choices = np.random.choice(outcomes, (n_simulations, n_trials))
cohort_choices                #(outcomes=heads,tails.  (sims #of rows, 3coins #of columns))
#be sure to sum across each simulation aka across each row (axis=1)
ds_counts = (cohort_choices == 'D').sum(axis=1)
(ds_counts == 2).mean()

0.06166

In [157]:
p_wdev = 0.75
p_ds = 0.25

n_trials = 10_000
n_billboards = 2


In [159]:
boards = np.random.random((n_trials, n_billboards))

In [160]:
DS_billboards = boards < p_ds
DS_billboards

array([[False, False],
       [ True,  True],
       [False, False],
       ...,
       [ True, False],
       [False,  True],
       [False,  True]])

In [ ]:
DS_billboards()

In [ ]:
DS = 1/4
WD = 3/4
outcomes = [DS, WD]

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?
(Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [18]:
outcomes = np.random.normal(mean, std_dev, 100000)

n_trials = 5
n_simulations = 100000

days = np.random.choice(outcomes, (n_simulations, n_trials))
days                #(outcomes=heads,tails.  (sims #of rows, 3coins #of columns))
#be sure to sum across each simulation aka across each row (axis=1)
pop_counts = (days).sum(axis=1)
(pop_counts <= 16).mean()

0.62081

### 5. Compare Heights

* Men have an average height of 178 cm and standard deviation of 8cm.
* Women have a mean of 170, sd = 6cm.
* Since you have means and standard deviations, you can use np.random.normal to generate observations.
* If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [162]:
male = np.random.normal(178, 8)
female = np.random.normal(170, 6) 
outcomes = (male, female)

n_trials = 2
n_simulations = 100000


ma_fem_arr = np.random.choice(outcomes, (n_simulations, n_trials))
ma_fem_arr


fem_grtr_male = np.all(np.diff(ma_fem_arr) < 0, axis=1)

(fem_grtr_male).mean()


0.25073

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [109]:
1/250

0.004

In [131]:
outcomes = tuple(range(1, 251))

n_trials = 50
n_simulations = 100_000


installs = np.random.choice(outcomes, (n_simulations, n_trials))
installs


issues = (installs == 1).sum(axis=1)
(issues < 1).mean()

0.81854

In [166]:
sims= 100000
installs = 50
fails= 1
success= 0
outcomes = [fails, success]
prob = 1/250

In [167]:
install_com = np.random.choice(outcomes, size=(sims, installs), p=[249/250, 1/250])
install_com

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [168]:
((install_com < prob).sum(axis=1) == 0).mean()

0.81995

100 students?

In [105]:
outcomes = tuple(range(1, 251))

n_trials = 100
n_simulations = 100_000


installs = np.random.choice(outcomes, (n_simulations, n_trials))



issues = (installs == 1).sum(axis=1)
(issues < 1).mean()

0.66949

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [32]:
outcomes = tuple(range(1, 251))

n_trials = 150
n_simulations = 100_000


installs = np.random.choice(outcomes, (n_simulations, n_trials))
installs


issues = (installs == 1).sum(axis=1)
(issues >= 1).mean()

0.45094

In [36]:
# sims= 100000
# installs = 150
# fails= 1
# success= 0
# outcomes = [success, fails]


In [34]:
# install_com = np.random.choice(outcomes, size=(sims, installs), p=[249/250, 1/250])
# install_com

In [33]:
# ((install_com > prob).sum(axis=1) == 1).mean()

How likely is it that 450 students all download anaconda without an issue?

In [169]:
outcomes = tuple(range(1, 251))

n_trials = 450
n_simulations = 100_000


installs = np.random.choice(outcomes, (n_simulations, n_trials))
installs


issues = (installs == 1).sum(axis=1)
(issues < 1).mean()


0.16558

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [152]:
n_rows= 1_000_000
n_cols= 3
food_truck=1
no_truck=0

data= np.random.random((n_rows,n_cols))

truck_prob = 0.7

((data < truck_prob).sum(axis=1)==0).mean()

0.02693

How likely is it that a food truck will show up sometime this week?

In [2]:
n_rows= 1_000_000
n_cols= 7
food_truck=1
no_truck=0

data= np.random.random((n_rows,n_cols))

truck_prob = 0.7

((data < truck_prob).sum(axis=1)==0).mean()

0.000224

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [54]:
outcomes = range(0, 365)
n_students = 23
n_sims = 10000
bd = np.random.choice(outcomes, (n_sims, n_students))
bd

array([[338, 316, 170, ..., 277,  28, 330],
       [237, 235, 306, ..., 258, 116, 261],
       [  3,  59, 112, ..., 138, 194, 252],
       ...,
       [312,  12, 198, ..., 122, 152, 151],
       [ 57,  25, 358, ..., 125, 143,  73],
       [352,  10, 200, ..., 268,  17, 329]])

In [55]:
n_unique = pd.DataFrame(bd).nunique(axis=1)
n_unique

0       23
1       23
2       22
3       22
4       23
        ..
9995    22
9996    21
9997    23
9998    21
9999    23
Length: 10000, dtype: int64

In [56]:
(n_unique > 22).mean()

0.4963

* What if it's 20 people? 

In [47]:
outcomes = range(0, 365)
n_students = 20
n_sims = 10000
bd = np.random.choice(outcomes, (n_sims, n_students))
bd

array([[  2,  13, 323, ...,  86, 146, 155],
       [120,  28, 323, ..., 156, 312, 350],
       [278, 156,  91, ..., 253, 186,  48],
       ...,
       [339,  99, 113, ...,  27, 109,  96],
       [306, 316, 176, ..., 334, 226, 116],
       [192, 162, 133, ..., 345, 342, 328]])

In [48]:
n_unique = pd.DataFrame(bd).nunique(axis=1)
n_unique

0       20
1       19
2       20
3       19
4       19
        ..
9995    20
9996    19
9997    20
9998    20
9999    20
Length: 10000, dtype: int64

In [51]:
(n_unique <= 19).mean()

0.4151

* 40?

In [57]:
outcomes = range(0, 365)
n_students = 40
n_sims = 10000
bd = np.random.choice(outcomes, (n_sims, n_students))
bd

array([[188, 350, 346, ..., 143, 123, 303],
       [ 76, 242, 312, ..., 199, 261,  20],
       [230, 341,  32, ..., 259, 355, 304],
       ...,
       [ 73, 208, 106, ...,  95, 324, 207],
       [ 67, 227, 233, ..., 251,  44, 226],
       [207, 364, 321, ..., 239, 341,  44]])

In [58]:
n_unique = pd.DataFrame(bd).nunique(axis=1)
n_unique

0       35
1       37
2       38
3       39
4       38
        ..
9995    39
9996    36
9997    40
9998    38
9999    39
Length: 10000, dtype: int64

In [59]:
(n_unique <= 39).mean()

0.8878